{
  fog_provider: 'AWS',
  fog_directory: 'htmlandcssclass.com',
  fog_region: 'us-west-1',
  aws_access_key_id: 'AKIAJ77PKMMEAGE7A7XA',
  aws_secret_access_key: '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'
}